### PR TITLE
Make the select element work freely

### PR DESCRIPTION
**Pull request by sahanDissanayake**

### CODE REVIEW

**Comment by javierbyte** [comment]
Looks interesting! But, what happens if you want to change the selected option outside the component? Changing the prop will have no effect because the component state will stay the same. Maybe we should set the active option from the state only if there is no active prop? (and have a different `defaultValue` prop to set the first state value?).

**Comment by sahanDissanayake** [comment]
Yup.. Are you thinking we should use `componentWillReceiveProps()` ?

**Comment by javierbyte** [comment]
Yeah, use `componentWillReceiveProps` and set the state when the prop can work. But maybe is better to add another prop `defaultValue` and set the state with it if you want an uncontrolled component, but maintain the `value` prop if you want a fully controlled component. What do you think?

**Comment by sahanDissanayake** [comment]
Lets try to keep it simple... lets not add more and more props... lets just make it work so that anyone can just plug this and get started to work on it

**Comment by javierbyte** [comment]
Thank you!!

**Pull request merged**
